config/routes.rb
BitsProject::Application.routes.draw do

	
     namespace :admin do
       resources :widgets	
       resources :videos
       resources :pages do
       	  scope :module => "pages" do
       	  resources :widgets
   	  	  end
   		end
       resource :session
       resource :refinement, :controller => "refinement" 
       resources :grids
       resources :categories
       resources :languages
     end

  match '*slug' => 'pages#show', :format => false
  

end

app/models/category.rb
class Category < ActiveRecord::Base
	validates_presence_of :name
	validates_length_of :name, :maximum => 100
	has_and_belongs_to_many :videos
	before_destroy {|category|  
		category.videos.clear
	}	
end

app/models/collection.rb
class Collection < ActiveRecord::Base
	belongs_to :widget
	before_save :form_unique_data
	
	serialize :data, Array
	
	def form_unique_data
		self.data.uniq!
	end
	
	def self.types
		[["Video","Video"]]
	end
	
	def self.find_all_for(model,options={})
		if options.blank?
			return model
		else
		  	refinements = model.join_category(options[:category]) unless options[:category].blank?
		  	if !options[:language].blank?
		  		if refinements
					refinements = refinements.join_language(options[:language])
				else
		  			refinements = model.join_language(options[:language])
				end
			end
		end
		refinements		
	end
end

app/models/grid.rb
class Grid < ActiveRecord::Base
	has_many :placeholders
	has_many :pages, :through => :placeholders
	
	validates_presence_of :width, :name, :color
	validates_uniqueness_of :width, :name, :color	
end

app/models/holding.rb
class Holding < ActiveRecord::Base
	belongs_to :widget
	belongs_to :placeholder
	
	validates_uniqueness_of :widget_id, :scope => :placeholder_id,
		:message => "already taken"
	validates_presence_of :widget_id, :placeholder_id
	
	before_save :validate_widget_width
	after_create :set_position
	
	def validate_widget_width
		if self.widget.width != self.placeholder.grid.width
			errors.add(:widget, "do not fit under the selected placeholder")
		end
	end
	
	def set_position
		self.position = self.id
		self.save
	end
	
	def move_up
		previous_holding = self.class.where("placeholder_id = #{self.placeholder_id} and  position < #{self.position}").first
		if previous_holding
			current_position = self.position
			previous_position = previous_holding.position
			self.update_attributes(:position => previous_position)
			previous_holding.update_attributes(:position => current_position)
	    end
	end
	
	def move_down
		next_holding = self.class.where("placeholder_id = #{self.placeholder_id} and position > #{self.position}").first
		if next_holding
			current_position = self.position
			next_position = next_holding.position
			self.update_attributes(:position => next_position)
			next_holding.update_attributes(:position => current_position)
	    end
	end
end

app/models/holdings.rb
class Holding < ActiveRecord::Base
	belongs_to :widget
	belongs_to :placeholder
end

app/models/language.rb
class Language < ActiveRecord::Base
	validates_presence_of :name
	validates_length_of :name, :maximum => 100
	has_and_belongs_to_many :videos
	before_destroy {|language|  
		language.videos.clear
	}		
end

app/models/layout.rb
class Layout < ActiveRecord::Base
	belongs_to :page
	belongs_to :placeholder
	has_many :placeholder_widgets
	has_many :widgets, :through => :placeholder_widgets
end

app/models/page.rb
class Page < ActiveRecord::Base
	has_many :placeholders, :order => "`row`, `column`", :dependent => :destroy
	has_many :grids, :through => :placeholders
	
	validates_presence_of :name, :slug
	validates_uniqueness_of :slug
	
	
	def self.build_by_id(id)
	  build_association.find(id)
	end
	
	def self.build_by_slug(slug)
	  build_association.find_by_slug(slug)	
	end
	
	def self.build_association
		includes(:placeholders => [:grid, :holdings,
					 :widgets])
	end
end

app/models/placeholder.rb
class Placeholder < ActiveRecord::Base
	belongs_to :page
	belongs_to :grid
	has_many :holdings, :order => "position", :dependent => :destroy
	has_many :widgets, :through => :holdings
	
	validates_presence_of :grid_id, :page_id, :row, :column
end

app/models/placeholder_widget.rb
class PlaceholderWidget < ActiveRecord::Base
	belongs_to :widget
	belongs_to :placeholder
end

app/models/template.rb
class Template < ActiveRecord::Base
	has_many :placeholders
	has_many :pages, :through => :placeholders
end

app/models/video.rb
class Video < ActiveRecord::Base
	has_and_belongs_to_many :languages
	has_and_belongs_to_many :categories
	validates_presence_of :name
	validates_length_of :name, :maximum => 255
	before_destroy {|video|  
		video.categories.clear
		video.languages.clear
	}	
	scope :join_category, lambda { |cat_id| joins(:categories).where(:categories_videos => {:category_id => cat_id }) }
	
	scope :join_language, lambda { |lan_id| joins(:languages).where(:languages_videos => {:language_id => lan_id }) }
end

app/models/widget.rb
class Widget < ActiveRecord::Base
	has_many :holdings, :dependent => :destroy
	has_many :collections, :dependent => :destroy
	has_many :placeholders, :through => :holdings
	serialize :properties, Hash
	
	validates_presence_of :filename, :unless => Proc.new{|w| w.is_advertisement?}  
	validates_length_of :name, :maximum => 255
	validates_presence_of :name, :width, :widget_type
	validate :json_format, :unless => lambda {|widget| widget.new_record? }
		
	FILETYPES = [
		["header", "/widgets/header.html.erb",966],
		["footer", "/widgets/footer.html.erb",966],
		["search", "/widgets/search.html.erb",165],
		["video_player", "/widgets/video_player.html.erb",485],
		["4 item slider", "/widgets/video_slider_485.html.erb",485],
		["header menu", "/widgets/header_menu.html.erb",966],
		["textualize", "/widgets/textualize.html.erb",966],
		["html5video", "/widgets/html5video_subtitle.html.erb",966],
		["home page static content", "/widgets/homepage_content.html.erb",485],
		["news ticker", "/widgets/news_ticker.html.erb",966],
		["Video gallery", "/widgets/video_gallery.html.erb",793]]

	before_save {|widget|
			widget.properties = JSON["#{widget.properties}"] if !widget.new_record?
	}
	def is_advertisement?
		widget_type == WidgetType::TYPES["Advertisement"]
	end
	
	#FIXME
	# I dont know why I did this
	def read_properties
		str = properties.to_json
		str = str.gsub("}", "\n}")
		str = str.gsub("},", "},\n")
		str = str.gsub("{", "{\n")
		str = str.gsub(",\"", ",\n\"")
		data = str.split("\n")
		indent = 0
		res = []
		data.each do |line|
			if indent > 1
				res << ("\t") * (indent -1) + line	
			else
				res <<  line	
			end
			 if line.include?("{") 
				 indent = indent + 1
			elsif  line.include?("}")
				 indent = indent - 1
			 end
			
		end
		res.join("\n")
	end
	:private
	def json_format
		errors.add(:properties,  "not in json format") unless properties_is_json?
	end
	
	def properties_is_json?
    begin
      !!JSON.parse(properties)
    rescue
      false
    end
  end
end

app/models/widget_type.rb
class WidgetType < ActiveRecord::Base
	
	TYPES =	{
		 "Regular" => 1,
		 "Advertisement" => 2,
		 "Video slider" => 3
		}
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	def show
		@page = Page.build_by_slug(params[:slug])
		render "public/404"   if @page.blank?
	end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
	def show
		@page = Page.build_by_slug("search")
	  	options = {}
	  	options.merge!(:category => params[:category]) unless params[:category].blank?
	  	options.merge!(:language => params[:language]) unless params[:language].blank?
	  	result = Collection.find_all_for(Video, options )
		@refinements = result.paginate(:page => params[:page], :per_page => 1)
		if @page.blank?
			render "public/404"   
		else
			render :template => "pages/show"
		end
	end
end

app/controllers/video_controller.rb
class VideoController < ApplicationController
	def show
		@page = Page.build_by_slug("video")
		@video = Video.find(params[:id])
		if @page.blank?
			render "public/404"   
		else
			render :template => "pages/show"
		end
	end
end

app/helpers/admin/pages_helper.rb
module Admin::PagesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
	def select_tag_for_categories(selected="")
		select_tag "category", options_from_collection_for_select(Category.all, "id", "name", {:prompt => "None"})

	end
	
	def select_tag_for_languages(selected="")
		select_tag "language", options_from_collection_for_select(Language.all, "id", "name"), {:prompt => "None"}
	end	
end

app/views/admin/_errors.html.erb
  <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>

app/views/admin/pages/_form.html.erb
	<div class="form_data">
		<div class="element">
			<label for"page_name">Name</label>
			<%= text_field :page, :name %>
		</div>
		<div class="element">
			<label for"page_slug">Slug</label>
			<%= text_field :page, :slug %>
		</div>
		<div class="element">
			<label for"page_slug">Style</label>
			<%= text_area :page, :style, :cols => 40, :rows => 5 %>
		</div>		
		<div class="form_end">
			<%= submit_tag "Save", :id => "save_page", :class => "button large green"%>
		</div>	
	</div>

app/views/admin/pages/edit.html.erb
<h2>Edit Page</h2>

<%= form_tag admin_page_path(@page.id), :class => "form_default", :method => :put do %>
	<%= render :partial => "form" %>
<% end %>

app/views/admin/pages/index.html.erb
<h2> List all available pages </h2>
<%= link_to "Add New page", new_admin_page_path, :class => "button link blue" %>
<table class="table">
	<tr>
		<th>#</th>
		<th>Name</th>
		<th>Slug</th>
		<th>Edit</th>
		<th>Manage widgets</th>
		<th>Delete</th>
	</tr>
	<% @pages.each_with_index do |page, index|%>
	<tr class=<%=cycle("odd","even")%> >
		<td><%= index +1 %></td>
		<td><%= page.name %></td>
		<td><%= page.slug %></td>
		<td> <%= link_to "Edit", edit_admin_page_path(page) %> </td>
		<td> <%= link_to "(+) Widgets", admin_page_widgets_path(page) %> </td>
		<td> <%= link_to "Delete", admin_page_path(page), :method => :delete, :confirm => "Are you sure?" %> </td>
	</tr>
	<% end %>
</table>

app/views/admin/pages/new.html.erb
<h2> Create a New Page </h2>
<p> Form a layout by adding different placeholders. </p>
<% if @page.errors.any? %>	
	<%= render :partial => "admin/errors", :locals => {:object => @page }%>
<% end %>
	<%= form_tag admin_pages_path, :class => "form_default" do %>
		<%= render :partial => "form" %>
		<div id="placeholders"style="display:none;">
		</div>		
	<% end %>
<br/>
<input type="button" id="add_placeholder" value="Add Placeholder"/>
<input type="button" id="clear_placeholder" value="Clear Placeholder"/>

<div id="build_layout">
	<div id="available_placeholders">
		<% @grids.each do |grid| %>
			<%= content_tag :div, 
				:class => "widget_width",
				:style => "background-color:#{grid.color};width:#{grid.width/2}px;", 
				"data-width" => grid.width,
				"data-template_id" => grid.id do %>
					<%= grid.name %> <%= grid.width %>
					<% end %>
		<% end %>
	</div>	
	<div id="page_layout">
	</div>
</div>

<%= content_for :internal_javascript do %>
	Admin.initilizePage();
<% end %>	