config/routes.rb
BitsProject::Application.routes.draw do

	
     namespace :admin do
       resources :widgets	
       resources :videos
       resources :pages do
       	  scope :module => "pages" do
       	  resources :widgets
   	  	  end
   		end
       resource :session
       resource :refinement, :controller => "refinement" 
       resources :grids
       resources :categories
       resources :languages
     end

  match '*slug' => 'pages#show', :format => false
  

end

app/models/widget.rb
class Widget < ActiveRecord::Base
	has_many :holdings, :dependent => :destroy
	has_many :collections, :dependent => :destroy
	has_many :placeholders, :through => :holdings
	serialize :properties, Hash
	
	validates_presence_of :filename, :unless => Proc.new{|w| w.is_advertisement?}  
	validates_length_of :name, :maximum => 255
	validates_presence_of :name, :width, :widget_type
	validate :json_format, :unless => lambda {|widget| widget.new_record? }
		
	FILETYPES = [
		["header", "/widgets/header.html.erb",966],
		["footer", "/widgets/footer.html.erb",966],
		["search", "/widgets/search.html.erb",165],
		["video_player", "/widgets/video_player.html.erb",485],
		["4 item slider", "/widgets/video_slider_485.html.erb",485],
		["header menu", "/widgets/header_menu.html.erb",966],
		["textualize", "/widgets/textualize.html.erb",966],
		["html5video", "/widgets/html5video_subtitle.html.erb",966],
		["home page static content", "/widgets/homepage_content.html.erb",485],
		["news ticker", "/widgets/news_ticker.html.erb",966],
		["Video gallery", "/widgets/video_gallery.html.erb",793]]

	before_save {|widget|
			widget.properties = JSON["#{widget.properties}"] if !widget.new_record?
	}
	def is_advertisement?
		widget_type == WidgetType::TYPES["Advertisement"]
	end
	
	#FIXME
	# I dont know why I did this
	def read_properties
		str = properties.to_json
		str = str.gsub("}", "\n}")
		str = str.gsub("},", "},\n")
		str = str.gsub("{", "{\n")
		str = str.gsub(",\"", ",\n\"")
		data = str.split("\n")
		indent = 0
		res = []
		data.each do |line|
			if indent > 1
				res << ("\t") * (indent -1) + line	
			else
				res <<  line	
			end
			 if line.include?("{") 
				 indent = indent + 1
			elsif  line.include?("}")
				 indent = indent - 1
			 end
			
		end
		res.join("\n")
	end
	:private
	def json_format
		errors.add(:properties,  "not in json format") unless properties_is_json?
	end
	
	def properties_is_json?
    begin
      !!JSON.parse(properties)
    rescue
      false
    end
  end
end

app/models/widget_type.rb
class WidgetType < ActiveRecord::Base
	
	TYPES =	{
		 "Regular" => 1,
		 "Advertisement" => 2,
		 "Video slider" => 3
		}
	
end

app/controllers/admin/pages/widgets_controller.rb
class Admin::Pages::WidgetsController < ApplicationController
	layout "admin"
	
	def index
		@page = Page.build_by_id(params[:page_id])
	end
	
	def create
		placeholder = Placeholder.find(params[:placeholder])
		res = placeholder.holdings.create(:widget_id => params[:widget])
		if res.errors.blank?
			flash[:notice] = "Widget added"
		else
			flash[:errors] = res.errors.full_messages.join("<br/>")
		end	
		redirect_to  admin_page_widgets_path(params[:page_id])
	end
	
	def update
	  current_holding = Holding.find_by_widget_id_and_placeholder_id(params[:id], params[:placeholder_id])
		if params[:direction] == "up"
		  current_holding.move_up
		elsif params[:direction] == "down" 
			current_holding.move_down
		end
	  redirect_to  admin_page_widgets_path(params[:page_id])	
	end
	
	def destroy
	  current_holding = Holding.find_by_widget_id_and_placeholder_id(params[:id], params[:placeholder_id])		
	  current_holding.destroy
	  redirect_to  admin_page_widgets_path(params[:page_id])
	end
end

app/controllers/admin/widgets_controller.rb
class Admin::WidgetsController < ApplicationController
layout 'admin'

	def index
		@widgets = Widget.all
	end
	
	def new
		@widget = Widget.new
	end
	
	def edit
		@widget = Widget.find(params[:id])
		@categories = Category.all
		@languages = Language.all
	end
	
	def update
		@widget = Widget.find(params[:id])
		if @widget.update_attributes(params[:widget])
			@widget.collections.each do |collection|
				params[:collection].merge!(:data => []) if params[:collection][:data].blank?
				collection.update_attributes(params[:collection])
			end
			redirect_to admin_widgets_path
		else
			render :action => :edit
		end
	end
	
	def create
		@widget = Widget.new(params[:widget])
		if @widget.save
			@widget.collections.create if @widget.widget_type == 3
			redirect_to admin_widgets_path
		else
			render :action => :new
		end		
	end
	
	def destroy
		Widget.destroy(params[:id])
		redirect_to admin_widgets_path
	end
	
end

app/helpers/admin/pages/widgets_helper.rb
module Admin::Pages::WidgetsHelper
	def option_tags_for_widgets(available_width)
	options = []
	Widget.where(:width => available_width).each do |widget|
	 options << content_tag(:option, widget.name, 
				 :value => widget.id,
				 "data-width" => widget.width).html_safe 
	end
	options
    end
end

app/helpers/admin/widgets_helper.rb
module Admin::WidgetsHelper
	def option_tags_for_filetypes
	options = []	
	Widget::FILETYPES.each do |opt|
		options << content_tag(:option, opt[0], 
			:value => opt[1],
			"data-width" => opt[2])
	 end
	 options
	end
end

app/views/admin/widgets/_collection.html.erb
<h2> Manage Widget Collections</h2>
<% @widget.collections.each do |collection| %>	
	<div class="element">
		<label for"collection_category">Type</label>
		<%= select :collection, :category, Collection.types %>
	</div>
	<div class="element">
		<label for"category">Category</label>
		<%= select_tag :category, options_from_collection_for_select(@categories, "id", "name"), {:prompt => "None"} %>
	</div>		
	<div class="element">
		<label for"language">Language</label>
		<%= select_tag :language, options_from_collection_for_select(@languages, "id", "name"), {:prompt => "None"} %>
		<input type="button" id="get_refinement" value="List" class="button large green"/>
	</div>	
	
	

			<div class="element video_group">
				<label>Available List</label>
				<div id="collection_list" class="collection_list"></div>	
			</div>		
			<div class="element video_group">
				<label>Selected List</label>	
					<%= render :partial => "collection_list", 
						:locals => {:collection => collection} %>
			</div>

<% end %>

<%= content_for :internal_javascript do %>
	$("#collection_list div").live("click",function(e) {
			var target = $(e.target);
			$('<input>').attr({
			    type: 'checkbox',
			    name: 'collection[data][]',
			    value: target.data('id')
			    }).prependTo(target);
			$("#add_to_list").append(target);	    
	});
	$("#get_refinement").click( function(e) {
		var queryData = {};
		queryData["type"] = $("#collection_category").val();
		queryData["category"] = $("#category").val();
		queryData["language"] = $("#language").val();
		$.ajax({
				type: "GET",
				url: "<%=admin_refinement_path%>",
				data: queryData,
				success: function(resp) {
					$("#collection_list").html(resp);	
				}
			});
		});
	$('#load_more_refinement').live('ajax:success', function(event, data){
		$(event.target).remove();
		$("#collection_list").append(data);
	});	
	
			
<% end %>	

app/views/admin/widgets/_collection_list.html.erb
<% unless collection.category.blank? or collection.data.blank?
   model = collection.category.constantize	
-%>	
<div class="collection_list" id="add_to_list">
<% Video.find(collection.data).each do |data|%>
	<%= check_box_tag "collection[data][]", data.id, true %> <%= data.name %>
<% end %>
</div>
<% else %>
	<div class="collection_list" id="add_to_list"></div>
<% end %>

app/views/admin/widgets/_rich_text_editor.html.erb
<%= javascript_include_tag "plugins/tinymce/jscripts/tiny_mce/tiny_mce.js" %>
<script type="text/javascript">
tinyMCE.init({
        // General options
        mode : "textareas",
        theme : "advanced",
        editor_selector : "richTextEditor",
        plugins : "autolink,lists,spellchecker,pagebreak,style,layer,table,save,advhr,advimage,advlink,emotions,iespell,inlinepopups,insertdatetime,preview,media,searchreplace,print,contextmenu,paste,directionality,fullscreen,noneditable,visualchars,nonbreaking,xhtmlxtras,template",

        // Theme options
        theme_advanced_buttons1 : "save,newdocument,|,bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,|,styleselect,formatselect,fontselect,fontsizeselect",
        theme_advanced_buttons2 : "cut,copy,paste,pastetext,pasteword,|,search,replace,|,bullist,numlist,|,outdent,indent,blockquote,|,undo,redo,|,link,unlink,anchor,image,cleanup,help,code,|,insertdate,inserttime,preview,|,forecolor,backcolor",
        theme_advanced_buttons3 : "tablecontrols,|,hr,removeformat,visualaid,|,sub,sup,|,charmap,emotions,iespell,media,advhr,|,print,|,ltr,rtl,|,fullscreen",
        theme_advanced_buttons4 : "insertlayer,moveforward,movebackward,absolute,|,styleprops,spellchecker,|,cite,abbr,acronym,del,ins,attribs,|,visualchars,nonbreaking,template,blockquote,pagebreak,|,insertfile,insertimage",
        theme_advanced_toolbar_location : "top",
        theme_advanced_toolbar_align : "left",
        theme_advanced_statusbar_location : "bottom",
        theme_advanced_resizing : true,

        // Skin options
        skin : "o2k7",
        skin_variant : "silver",

        // Example content CSS (should be your site CSS)
        content_css : "css/example.css",

        // Drop lists for link/image/media/template dialogs
        template_external_list_url : "js/template_list.js",
        external_link_list_url : "js/link_list.js",
        external_image_list_url : "js/image_list.js",
        media_external_list_url : "js/media_list.js",

        // Replace values for the template plugin
        template_replace_values : {
                username : "Some User",
                staffid : "991234"
        }
});
</script>

app/views/admin/widgets/edit.html.erb
<h2> Edit widget </h2>
<% if @widget.errors.any? %>
	<%= render :partial => "admin/errors", :locals => {:object => @widget }%>
<% end %>
<%= form_tag admin_widget_path(@widget), :method => :put, :class => "form_default"  do %>
<div class="form_data">	
<div class="element">
	<label for"widget_name">Name</label>
	<%= text_field :widget, :name %>
</div>
<div class="element">
	<label for"widget_width">Width</label>
	<%= text_field :widget, :width, :readonly => true, :disabled => true %>
</div>
<div class="element">
	<label for"widget_width">Filename</label>
	<%= text_field :widget, :filename, :readonly => true, :disabled => true %>
</div>
	
	<div class="element">
		<% if @widget.widget_type == WidgetType::TYPES["Advertisement"] %>
			<label for"widget_code">Ad Script</label>
			<%= text_area :widget, :style, :rows => 5, :cols => 40 %>
		<% else %>
			<label for"widget_code">Widget Styles</label>
			<%= text_area :widget, :style, :rows => 5, :cols => 40 %>
		<% end %>
	</div>
	<% if @widget.widget_type == WidgetType::TYPES["Video slider"] %>
		<%= render :partial => "collection"%>
	<% end %>		
	<div class="form_save">
		<%= submit_tag "Save", :class => "button large green" %>
		<%= link_to "Cancel", edit_admin_widget_path(@widget), :class => "button link  blue"%>
	</div>
</div>	
<% end %>

app/views/admin/widgets/index.html.erb
<h2> List all available widgets </h2>
<%= link_to "Add New Widget", new_admin_widget_path, :class => "button link blue" %>
<table class="table">
	<tr>
		<th>#</th>
		<th>Name</th>
		<th>width</th>
		<th>Edit</th>
		<th>Delete</th>
	</tr>
	<% @widgets.each_with_index do |widget, index|%>
	<tr class=<%=cycle("odd","even")%> >
		<td><%= index +1 %></td>
		<td><%= widget.name %></td>
		<td><%= widget.width %></td>
		<td> <%= link_to "Edit", edit_admin_widget_path(widget)%></td>
		<td> <%= link_to "Delete", admin_widget_path(widget), :method => :delete, 
			:confirm => "Delete will remove from pages where this widget is used \n Are you sure?"%></td>
	</tr>
	<% end %>
</table>

app/views/admin/widgets/new.html.erb
<h2> Add a new widget </h2>
<% if @widget.errors.any? %>
	<%= render :partial => "admin/errors", :locals => {:object => @widget }%>
<% end %>

<%= form_tag admin_widgets_path, :class => "form_default" do %>
<div class="form_data">
<div class="element">
	<label for"widget_name">Name</label>
	<%= text_field :widget, :name %>
</div>
<div class="element">
	<label for"widget_width">Width</label>
<%= select("widget", "width", 
	options_for_select(Grid.all.collect {|g| [ g.width, g.width ] }),
	 {:prompt => 'Widget Width'}) %>	
</div>
<div class="element">
	<label for"widget_filename">File name</label>
	<select name="widget[filename]" id="widget_filename">
		<option vlue="">Select filename</option>
		<%= option_tags_for_filetypes.each do |option| %>
			<%= option %>
		<% end %>
	</select>	
</div>

<div class="element">
	<label for"widget_filename">Widget Type</label>
<%= select("widget", "widget_type", 
	options_for_select(WidgetType.all.collect {|w| [ w.name, w.id ] }),
	 {:prompt => 'Widget Type'}) %>
</div>
<div class="form_save">
	 <%= submit_tag "Save", :class => "button large green"%>
	 <%= link_to "Cancel", admin_widgets_path, :class => "button link  blue"%>
</div>
</div>
<% end %>
<%= content_for :internal_javascript do %>
	Admin.initWidget();	
<% end %>