config/routes.rb
BitsProject::Application.routes.draw do

	
     namespace :admin do
       resources :widgets	
       resources :videos
       resources :pages do
       	  scope :module => "pages" do
       	  resources :widgets
   	  	  end
   		end
       resource :session
       resource :refinement, :controller => "refinement" 
       resources :grids
       resources :categories
       resources :languages
     end

  match '*slug' => 'pages#show', :format => false
  

end

app/models/grid.rb
class Grid < ActiveRecord::Base
	has_many :placeholders
	has_many :pages, :through => :placeholders
	
	validates_presence_of :width, :name, :color
	validates_uniqueness_of :width, :name, :color	
end

app/controllers/admin/grids_controller.rb
class Admin::GridsController < ApplicationController
layout 'admin'
	def index
		@grids = Grid.all
	end
		
	def create
		@grid = Grid.new(params[:grid])
		if @grid.save
			redirect_to admin_grids_path
		else
			render :action => "new"
		end
	end
	
	def new
		@grid = Grid.new
	end
	
	def edit
		@grid = Grid.find(params[:id])
	end
	
	def update
		@grid = Grid.find(params[:id])
		if @grid.update_attributes(params[:grid])
			redirect_to admin_grids_path
		else
			render :action => "edit"
		end
	end
end

app/views/admin/grids/_form.html.erb
<div class="form_data">
<div class="element">
	<label for"grid_name">Name</label>
	<%= text_field :grid, :name %>
</div>
<div class="element">
	<label for"grid_width">Width</label>
	<%= text_field :grid, :width %>
</div>
<div class="element">
	<label for"grid_color">Color</label>
	<%= text_field :grid, :color %>
</div>
<div class="form_save">
	<%= submit_tag "Save", :class => "button large green"%>
</div>
</div>

app/views/admin/grids/edit.html.erb
<h2> Edit grid </h2>
<%= form_tag admin_grid_path(@grid), :method => :put, :class => "form_default" do %>
	<%= render :partial => "form"%>
<% end %>

app/views/admin/grids/index.html.erb
<h2> List all available grids </h2>
<%= link_to "Add New Grid", new_admin_grid_path, :class => "button link blue" %>
<table class="table">
	<tr>
		<th>#</th>
		<th>Name</th>
		<th>Width</th>
		<th>Color</th>
		<th>Edit</th>
	</tr>
	<% @grids.each_with_index do |grid, index|%>
	<tr class=<%=cycle("odd","even")%> >
		<td><%= index +1 %></td>
		<td><%= grid.name %></td>
		<td><%= grid.width %></td>
		<td> <span class="small_box" style="background-color:<%= grid.color %>;">&nbsp;</span></td>
		<td> <%= link_to "Edit", edit_admin_grid_path(grid)%></td>
	</tr>
	<% end %>
</table>

app/views/admin/grids/new.html.erb
<h2> Add a new grid </h2>
<%= form_tag admin_grids_path, :class => "form_default" do %>
<%= render :partial => "form"%>
<% end %>