config/routes.rb
BitsProject::Application.routes.draw do

	
     namespace :admin do
       resources :widgets	
       resources :videos
       resources :pages do
       	  scope :module => "pages" do
       	  resources :widgets
   	  	  end
   		end
       resource :session
       resource :refinement, :controller => "refinement" 
       resources :grids
       resources :categories
       resources :languages
     end

  match '*slug' => 'pages#show', :format => false
  

end

app/models/video.rb
class Video < ActiveRecord::Base
	has_and_belongs_to_many :languages
	has_and_belongs_to_many :categories
	validates_presence_of :name
	validates_length_of :name, :maximum => 255
	before_destroy {|video|  
		video.categories.clear
		video.languages.clear
	}	
	scope :join_category, lambda { |cat_id| joins(:categories).where(:categories_videos => {:category_id => cat_id }) }
	
	scope :join_language, lambda { |lan_id| joins(:languages).where(:languages_videos => {:language_id => lan_id }) }
end

app/controllers/admin/videos_controller.rb
class Admin::VideosController < ApplicationController
layout 'admin'

	def index
		@videos = Video.paginate(:page => params[:page], :per_page => 10)
	end
	
	def new
		@video = Video.new
		@categories = Category.all
		@languages = Language.all
	end
	
	def edit
		@video = Video.find(params[:id])
		@categories = Category.all
		@languages = Language.all
	end
	
	def update
		@video = Video.find(params[:id])
		if @video.update_attributes(params[:video])
			redirect_to admin_videos_path
		else
			render :action => :edit
		end
	end
	
	def create
		@video = Video.new(params[:video])
		if @video.save
			redirect_to admin_videos_path
		else
			render :action => :new
		end		
	end
	
	def destroy
		Video.destroy(params[:id])
		redirect_to admin_videos_path
	end
end

app/controllers/video_controller.rb
class VideoController < ApplicationController
	def show
		@page = Page.build_by_slug("video")
		@video = Video.find(params[:id])
		if @page.blank?
			render "public/404"   
		else
			render :template => "pages/show"
		end
	end
end

app/views/admin/videos/_form.html.erb
<div class="form_data">
<div class="element">
	<label for"video_name">Name</label>
	<%= text_field :video, :name %>
</div>
<div class="element">
	<label for"video_thumbnail">Thumbnail</label>
	<%= text_field :video, :thumbnail %>
</div>
<div class="element">
	<label for"video_description">Description</label>
	<%= text_area :video, :description, :rows => 5, :cols => 40 %>
</div>
<div class="element">
	<label for"video_embed_src">Embed SRC</label>
	<%= text_area :video, :embed_src, :rows => 5, :cols => 40 %>
</div>
<div class="element video_group">
	<label for"video_embed_src">Categories</label>
	<div class="collection_list">
		<% @categories.each do |category| %>
		<div class="list_collection">
		<%= check_box_tag "video[category_ids][]", category.id, @video.categories.include?(category) %> <%= category.name %>
		</div>
		<% end %>
	</div>	
</div>	
<div class="element video_group">
	<label for"video_embed_src">Languages</label>
	<div class="collection_list">
		<% @languages.each do |language| %>
		<div class="list_collection">
		<%= check_box_tag "video[language_ids][]", language.id, @video.languages.include?(language) %> <%= language.name %>
		</div>
		<% end %>
	</div>	
</div>

<div class="form_save">
	<%= submit_tag "Save", :class => "button large green"%>
</div>
</div>

app/views/admin/videos/edit.html.erb
<h2> Edit Video </h2>
<%= form_tag admin_video_path(@video), :method => :put, :class => "form_default"  do %>
	<%= render :partial => "form"%>
<% end %>

app/views/admin/videos/index.html.erb
<h2> List all available videos </h2>
<%= link_to "Add New Video", new_admin_video_path, :class => "button link blue" %>
<table class="table">
	<tr>
		<th>#</th>
		<th>Name</th>
		<th>Thumbnail</th>
		<th>Description</th>
		<th>Edit</th>
		<th>Delete</th>
	</tr>
	<% @videos.each_with_index do |video, index|%>
	<tr class=<%=cycle("odd","even")%> >
		<td><%= index +1 %></td>
		<td><%= video.name %></td>
		<td><%= video.thumbnail %></td>
		<td><%= video.description %></td>
		<td> <%= link_to "Edit", edit_admin_video_path(video)%></td>
		<td> <%= link_to "Delete", admin_video_path(video), :method => :delete, :confirm => "Are you sure?"%></td>
	</tr>
	<% end %>
	<%= will_paginate @videos %>
</table>

app/views/admin/videos/new.html.erb
<h2> Add a new video </h2>
<%= form_tag admin_videos_path, :class => "form_default" do %>
<%= render :partial => "form"%>
<% end %>